Destructure code and add login.
IamSwap/express-mongo-example pull request #1
Opened 2022-06-29 14:47 UTC by yo9e5h

- Destructure the code.
- Move secrets to .env
- Add bcrypt for password hash and verification.
- Login and register.

2022-06-30 12:25 UTC, IamSwap requested changes

2022-06-30 12:25 UTC, IamSwap commented on .gitignore
> +.pnp.*
Do we really need all of these paths in `.gitignore`?

2022-06-30 12:25 UTC, IamSwap commented on routes/login.js
> +  return res.json({ message: "Welcome aboard!" });
Here we should return the authenticated user with an access token. 
That access token can be used for authenticating other endpoints.

2022-06-30 12:25 UTC, IamSwap commented on utils/connection.js
> +  const client = new MongoClient(process.env.DATABASE_URL, {
There should an `.env.example` file to set these variables.

2022-07-04 05:07 UTC, yo9e5h commented
- remove excess .gitignores
- add .env.example
- send token after register.

2022-07-04 06:00 UTC, IamSwap approved these changes

2022-07-04 06:00 UTC, merged